name: Publish MkDocs site

on:
  push:
    branches:
      - main # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true # so gh-pages push works
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-git-revision-date-localized-plugin
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
